### ISSUE TITLE
req support for Python 3

### ISSUE THREAD

**Issue by paregorios** [mromanello/hucitlib#3]
Evidently this package only works with Python 2. The diagnostic error is that install with pip under Python 3.6.5 OSX El Capitan (10.11.6) fails:

```
$ pip install hucitlib
Collecting hucitlib
  Downloading https://files.pythonhosted.org/packages/80/8a/768433eba0d9ae07efae3b4f170a6c15dd9484296ab5c05aba292fe91c17/hucitlib-0.2.8.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z8/2zsyr5dn2cl06wl3fwz3f2_00000gp/T/pip-install-mr7vicxo/hucitlib/setup.py", line 5, in <module>
        execfile('{0}/__version__.py'.format(NAME))
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z8/2zsyr5dn2cl06wl3fwz3f2_00000gp/T/pip-install-mr7vicxo/hucitlib/

```

Also cannot use git clone and setup.py. Same error:

```
$ git clone https://github.com/mromanello/hucit_kb.git
Cloning into 'hucit_kb'...
remote: Counting objects: 590, done.
remote: Total 590 (delta 0), reused 0 (delta 0), pack-reused 590
Receiving objects: 100% (590/590), 6.29 MiB | 3.23 MiB/s, done.
Resolving deltas: 100% (326/326), done.
$ cd hucit_kb/
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    execfile('{0}/__version__.py'.format(NAME))
NameError: name 'execfile' is not defined
```

**Comment by paregorios** [comment]
I'm going to take a shot at this in https://github.com/paregorios/hucit_kb/tree/python3 and will issue a PR if successful.

**Comment by paregorios** [comment]
Nope. This is blocked at least by the dependency on [Surf](https://github.com/cosminbasca/surfrdf), which seems only to be available for 2.x. They have [an FR for Python 3](https://github.com/cosminbasca/surfrdf/issues/5), but that work seems to have stalled in 2016 (sic). 

I note here that [official support for Python 2 ends on 1 January 2020](https://pythonclock.org/).

**Comment by paregorios** [comment]
I've spent a couple hours trying to upgrade Surf to python 3 and the errors I'm getitng from its tests are beyond my ability to resolve. So this is a dead end for me.

**Comment by mromanello** [comment]
ok, after having run the tests for [this branch](https://github.com/funkyfuture/surfrdf/tree/python3) I believe this is where something goes wrong: https://github.com/cosminbasca/surfrdf/blob/master/surf/util.py#L321-L349 

it's the function responsible for mapping values to their rdflib equivalent and, for some reason, it's casting a unicode string into a `base64Binary`.

**Comment by PonteIneptique** [comment]
Got  bored : https://travis-ci.org/PonteIneptique/surfrdf/builds/427108539

**Comment by PonteIneptique** [comment]
(I am saying this way because I am super happy about it :p )

**Comment by PonteIneptique** [comment]
Note that if this works, I expect to see Hucit really soon in Py3 :dagger:  :dagger:  :dagger:  ahah

**Comment by mromanello** [comment]
@PonteIneptique this is fantastic news! so glad and thankful that you got bored ;-) I hope your PR will soon be merged into the main branch, otherwise I'll be happy to use your fork.

And, yes, this was *the* issue keeping me from migrating my whole citation-extraction framework to Py3.

**Comment by PonteIneptique** [comment]
Note, if you want to try to move to Py3, you can install using `pip install https://github.com/PonteIneptique/surfrdf/archive/master.zip`. This can be a way to start dev :) (Not that I am pushing you. Not really at least. Well... hehe)

**Comment by mromanello** [comment]
@paregorios @PonteIneptique  It took a loooong time, but I'm happy to report that a first version of `hucitlib` now supports Python 3. 

As I haven't found a way yet to install Thibault's `surf` from `setup.py` (suggestions welcome!) you will need to clone this repo, check out branch `issue-3/py3` and install it from there after running `pip install -r requirements.txt`. 

Unfortunately, this branch cannot (yet) being merged into master as I have another library (my [CitationExtractor](https://github.com/mromanello/CitationExtractor)) relying on `hucitlib` which still needs to be ported to Python 3.

**Comment by mromanello** [comment]
`issue-3/py3` has been now merged with `master`, so the library runs works under Py3
